### ISSUE TITLE
Statging server error

### ISSUE THREAD

**Issue by gausma** [throneless-tech/libsignal-service-javascript#17]
When I register in productive mode everything is running fine.
Registration on the staging server is possible too. But sending a message results in the following error.
Is the a known problem, a changed protocol or something else?

H:\Projekte\Node-RED\libsignal-service-javascript>node .\examples\client.js send +xxxxxxxxxxx "PING"
(node:1508) V8: H:\Projekte\Node-RED\libsignal-service-javascript\node_modules\@throneless\libsignal-protocol\build\curve25519_concat.js:20225 Invalid asm.js: Expected shift of word size
(Use `node --trace-warnings ...` to show where the warning was created)
V1 session storage migration error: registrationId undefined for open session version undefined
V1 session storage migration error: registrationId undefined for open session version undefined
{
  successfulIdentifiers: [],
  failoverIdentifiers: [],
  errors: [
    SendMessageNetworkError: The server rejected our query, please file a bug report. (original: promiseAjax: error response; code: 503)
        at new ReplayableError (H:\Projekte\Node-RED\libsignal-service-javascript\src\errors.js:22:13)
        at new SendMessageNetworkError (H:\Projekte\Node-RED\libsignal-service-javascript\src\errors.js:69:5)
        at H:\Projekte\Node-RED\libsignal-service-javascript\src\OutgoingMessage.js:234:15
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async OutgoingMessage.sendToIdentifier (H:\Projekte\Node-RED\libsignal-service-javascript\src\OutgoingMessage.js:519:7)
    Original stack:
    HTTPError: promiseAjax: error response; code: 503
        at HTTPError (H:\Projekte\Node-RED\libsignal-service-javascript\src\WebAPI.js:391:13)
        at H:\Projekte\Node-RED\libsignal-service-javascript\src\WebAPI.js:347:13
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
    Original stack:
    Error
        at _outerAjax (H:\Projekte\Node-RED\libsignal-service-javascript\src\WebAPI.js:385:19)
        at _ajax (H:\Projekte\Node-RED\libsignal-service-javascript\src\WebAPI.js:517:14)
        at Object.sendMessages (H:\Projekte\Node-RED\libsignal-service-javascript\src\WebAPI.js:887:14)
        at OutgoingMessage.transmitMessage (H:\Projekte\Node-RED\libsignal-service-javascript\src\OutgoingMessage.js:217:29)
        at H:\Projekte\Node-RED\libsignal-service-javascript\src\OutgoingMessage.js:383:21
        at async OutgoingMessage.sendToIdentifier (H:\Projekte\Node-RED\libsignal-service-javascript\src\OutgoingMessage.js:519:7) {
      functionCode: undefined,
      identifier: '+xxxxxxxxxxx',
      code: 503,
      reason: 'Failed to create or send message'
    }
  ],
  unidentifiedDeliveries: [],
  dataMessage: <Buffer 0a 04 50 49 4e 47 32 08 06 42 76 64 3b 1b 4b 95 38 f0 8a 9a 89 f2 2e>
}

**Comment by jheretic** [comment]
Hey, thanks for the report! That's super weird that it's working on production and not staging. Can you let me know what version of node you're using?
