### ISSUE TITLE
401 Unauthorized when registering account

### ISSUE THREAD

**Issue by Shipibo303** [throneless-tech/libsignal-service-javascript#37]
I get 401 - Unauthorized error when sending a verification code. 

This is the code I used to verify the account:

`const protocolStore = new Signal.ProtocolStore(new Storage("./data"));
protocolStore.load();
const accountManager = new Signal.AccountManager("+420XXXXX", "XXCXX", protocolStore);

  rl.question("Insert code: ", function(res) {
      console.log(res);
      accountManager.registerSingleDevice(res.trim()).then(result => {
      console.log("Registered account.");
      rl.close();
});
  }); `

It didn't work with any number I tried.

This is the console output:

`(node:93924) UnhandledPromiseRejectionWarning: HTTPError: promiseAjax: error response; code: 401
    at HTTPError (D:\SCRIPTS\DignalServer\signal_bridge\node_modules\@throneless\libsignal-service\src\WebAPI.js:389:13)
    at resultPromise.then.result (D:\SCRIPTS\DignalServer\signal_bridge\node_modules\@throneless\libsignal-service\src\WebAPI.js:345:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Original stack:
Error
    at _outerAjax (D:\SCRIPTS\DignalServer\signal_bridge\node_modules\@throneless\libsignal-service\src\WebAPI.js:383:19)
    at _ajax (D:\SCRIPTS\DignalServer\signal_bridge\node_modules\@throneless\libsignal-service\src\WebAPI.js:502:14)
    at Object.registerKeys (D:\SCRIPTS\DignalServer\signal_bridge\node_modules\@throneless\libsignal-service\src\WebAPI.js:737:14)
    at createAccount.then.then.then.keys (D:\SCRIPTS\DignalServer\signal_bridge\node_modules\@throneless\libsignal-service\src\AccountManager.js:134:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:93924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:93924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Do someone know how to get past this issue or what I'm doing wrong?

Thank you

**Comment by bubi1311** [comment]
@Shipibo303 
Seems to be the same problem as described here: https://github.com/gausma/nodered-contrib-signal-client/issues/29#issuecomment-913198928 

In my opinion the change 'Retire AmbiguousIdentifier' causes the problem: https://github.com/signalapp/Signal-Server/commit/d1735c7e57c4111516cbdc8a6ca69eaf73cf8290#diff-1930f0e12a3248859cbe444051589f7836a00e76b0247ce0ad5549fb8d8bfbb7 
I guess line 328/329 in the diff of AccountController.java can be a point to start.

I'm not a js developer so I'm not a good support to solve this. I'm sorry :-(

**Comment by revoltek-daniel** [comment]
It looks like they changed username (phonenumber) to uuid, so the basic auth requires the uuid instead of the username

its not nice but this is working for me on registration (ignore the formatting issues):
https://github.com/gausma/libsignal-service-javascript/compare/master...revoltek-daniel:master

But to send messages you need the uuid of the person you want to send the message to. Till now i've found no way how to solve that. the getProfile method needed also the uuid. I think the uuid is retrieved when the address book is compared. Will look into this if i found enough spare time
